@startuml

database "Mongo" {
package "Remote Workflow" {
  component task_1
  component task_2


  component task_n
}
}
package "TaskRunner" as interface {
    
}

TaskRunner ..> [Task: TL AddAffiliation] : Do(), Validate(), Rollback()
TaskRunner ..> [Task: Send Remote Config] : Do(), Validate(), Rollback()
TaskRunner ..> [Task: TL Save Remote Config] : Rollback

@enduml
