@startuml
start
:Start gRPC server;

while ("Received Message from Remote Client") is (Ok)
    :WorkflowNameKey Ok?;

    :initialize
        Workflow Config;

    :Process Remote Messages
        Log Remote Output
        Remote Task1 Success
            .....
        Remote Task2 Error;


    :Start or Resume Server Workflow
        Run TL Tasks
            (...3 -> n)
        Stop if...
        Remote Tasks are next;

    :Send Remote Tasks To Do;
endwhile

-Workflow Completed or any Error

-Save Workflow Progress
stop
@enduml