@startuml
hide footbox

actor RemoteUser
boundary "Remote"
entity ServerWorkflow
collections "Server Workflows[]"
database "Workflows State in Mongo"

RemoteUser  --> ServerWorkflow : gRPC::SendWorkflowNameKey()
ServerWorkflow <- "Server Workflows[]" : NewWorkflow( workflowNameKey )
    Activate ServerWorkflow
    ServerWorkflow <- "Workflows State in Mongo": NewWorkflow( config )
    ServerWorkflow ->  ServerWorkflow : RunMandatoryTasks()
    ServerWorkflow  --> Remote : Config <- gRPC::SendConfig()

        Activate Remote
        Remote -> Remote : consume config
        Remote --> ServerWorkflow : gRPC:: SendTaskCompletionToServer()
        ServerWorkflow -> ServerWorkflow : Run() -> Server Tasks
        ServerWorkflow --> "Remote" : gRPC::SendRemoteTasks()
        Remote -> Remote : runRemoteSentWorkflow()
        Remote --> ServerWorkflow : gRPC::SendRemoteTasksProgress()
        ServerWorkflow -> ServerWorkflow : CopyRemoteTasksProgress()
        ServerWorkflow -> ServerWorkflow : Run() -> Resume Tasks
        ServerWorkflow --> Remote : gRPC::SendWorkflowCompletion()
        Remote --> ServerWorkflow !! : gRPC::SendClose()
        return

    ServerWorkflow -> ServerWorkflow : Workflow.Save()
    ServerWorkflow -> "Workflows State in Mongo" : Save()

    return
@enduml
